
// Mock data for authors
export const authors = [
  {
    id: "1",
    name: "J.K. Rowling",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1288&auto=format&fit=crop",
    bio: "Joanne Rowling CH, OBE, HonFRSE, FRCPE, FRSL, better known by her pen name J. K. Rowling, is a British author and philanthropist. She wrote Harry Potter, a seven-volume fantasy series published from 1997 to 2007.",
    birthdate: "July 31, 1965",
    birthplace: "Yate, Gloucestershire, England",
    books: 14,
    genre: "Fantasy",
  },
  {
    id: "2",
    name: "Stephen King",
    image: "https://images.unsplash.com/photo-1567515004624-219c11d31f2e??q=80&w=1288&auto=format&fit=crop",
    bio: "Stephen Edwin King is an American author of horror, supernatural fiction, suspense, crime, science-fiction, and fantasy novels. Described as the 'King of Horror', his books have sold more than 350 million copies.",
    birthdate: "September 21, 1947",
    birthplace: "Portland, Maine, USA",
    books: 64,
    genre: "Horror",
  },
  {
    id: "3",
    name: "Jane Austen",
    image: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?q=80&w=1287&auto=format&fit=crop",
    bio: "Jane Austen was an English novelist known primarily for her six major novels, which interpret, critique and comment upon the British landed gentry at the end of the 18th century.",
    birthdate: "December 16, 1775",
    birthplace: "Steventon, Hampshire, England",
    books: 6,
    genre: "Classic Literature",
  },
  {
    id: "4",
    name: "George R.R. Martin",
    image: "https://images.unsplash.com/photo-1566753323558-f4e0952af115?q=80&w=1321&auto=format&fit=crop",
    bio: "George Raymond Richard Martin, also known as GRRM, is an American novelist, screenwriter, television producer and short story writer. He is the author of the series of epic fantasy novels A Song of Ice and Fire, which was adapted into the Emmy Award-winning HBO series Game of Thrones.",
    birthdate: "September 20, 1948",
    birthplace: "Bayonne, New Jersey, USA",
    books: 29,
    genre: "Fantasy",
  },
  {
    id: "5",
    name: "Agatha Christie",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=1470&auto=format&fit=crop",
    bio: "Dame Agatha Mary Clarissa Christie, Lady Mallowan, DBE was an English writer known for her 66 detective novels and 14 short story collections, particularly those revolving around fictional detectives Hercule Poirot and Miss Marple.",
    birthdate: "September 15, 1890",
    birthplace: "Torquay, Devon, England",
    books: 66,
    genre: "Mystery",
  },
  {
    id: "6",
    name: "Haruki Murakami",
    image: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?q=80&w=1287&auto=format&fit=crop",
    bio: "Haruki Murakami is a Japanese writer. His novels, essays, and short stories have been bestsellers in Japan and internationally, with his work translated into 50 languages and has sold millions of copies outside Japan.",
    birthdate: "January 12, 1949",
    birthplace: "Kyoto, Japan",
    books: 14,
    genre: "Magical Realism",
  },
  {
    id: "7",
    name: "Toni Morrison",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1288&auto=format&fit=crop",
    bio: "Toni Morrison was an American novelist, essayist, book editor, and college professor. Her first novel, The Bluest Eye, was published in 1970. The critically acclaimed Song of Solomon brought her national attention and won the National Book Critics Circle Award.",
    birthdate: "February 18, 1931",
    birthplace: "Lorain, Ohio, USA",
    books: 11,
    genre: "Literary Fiction",
  },
  {
    id: "8",
    name: "Neil Gaiman",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1287&auto=format&fit=crop",
    bio: "Neil Richard MacKinnon Gaiman is an English author of short fiction, novels, comic books, graphic novels, nonfiction, audio theatre, and films. His works include the comic book series The Sandman and novels Stardust, American Gods, Coraline, and The Graveyard Book.",
    birthdate: "November 10, 1960",
    birthplace: "Portchester, Hampshire, England",
    books: 19,
    genre: "Fantasy",
  },
];
