
// Mock data for publishers
export const publishers = [
  {
    id: "1",
    name: "Penguin Random House",
    logo: "https://images.unsplash.com/photo-1571867424488-4565932edb41?q=80&w=1287&auto=format&fit=crop",
    description: "Penguin Random House LLC is an American multinational conglomerate publishing company formed in 2013 from the merger of Penguin Group and Random House.",
    founded: 2013,
    headquarters: "New York City, USA",
    website: "https://www.penguinrandomhouse.com",
    verified: true,
  },
  {
    id: "2",
    name: "HarperCollins",
    logo: "https://images.unsplash.com/photo-1616514197671-15d99ce7253f?q=80&w=1473&auto=format&fit=crop",
    description: "HarperCollins Publishers LLC is one of the world's largest publishing companies and is one of the Big Five English-language publishing companies, alongside Penguin Random House, Simon & Schuster, Hachette, and Macmillan.",
    founded: 1989,
    headquarters: "New York City, USA",
    website: "https://www.harpercollins.com",
    verified: true,
  },
  {
    id: "3",
    name: "Simon & Schuster",
    logo: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=1512&auto=format&fit=crop",
    description: "Simon & Schuster, Inc., a subsidiary of Paramount Global, is an American publishing company founded in New York City in 1924 by Richard L. Simon and M. Lincoln Schuster.",
    founded: 1924,
    headquarters: "New York City, USA",
    website: "https://www.simonandschuster.com",
    verified: true,
  },
  {
    id: "4",
    name: "Macmillan Publishers",
    logo: "https://images.unsplash.com/photo-1542744095-291d1f67b221?q=80&w=1520&auto=format&fit=crop",
    description: "Macmillan Publishers Ltd is a British publishing company owned by the German Holtzbrinck Publishing Group. It has offices in 41 countries worldwide and operates in more than 30 others.",
    founded: 1843,
    headquarters: "London, UK",
    website: "https://us.macmillan.com",
    verified: true,
  },
  {
    id: "5",
    name: "Hachette Book Group",
    logo: "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?q=80&w=1287&auto=format&fit=crop",
    description: "Hachette Book Group is a publishing company owned by Hachette Livre, the largest publishing company in France, and the third largest trade and educational publisher in the world.",
    founded: 2006,
    headquarters: "New York City, USA",
    website: "https://www.hachettebookgroup.com",
    verified: true,
  },
  {
    id: "6",
    name: "Scholastic Corporation",
    logo: "https://images.unsplash.com/photo-1447933601403-0c44eafe6001?q=80&w=1322&auto=format&fit=crop",
    description: "Scholastic Corporation is an American multinational publishing, education and media company that publishes and distributes books, comics, and educational materials for schools, parents, and children.",
    founded: 1920,
    headquarters: "New York City, USA",
    website: "https://www.scholastic.com",
    verified: true,
  },
  {
    id: "7",
    name: "Bloomsbury Publishing",
    logo: "https://images.unsplash.com/photo-1596120236172-231999844ade?q=80&w=1287&auto=format&fit=crop",
    description: "Bloomsbury Publishing plc is a British worldwide publishing house of fiction and non-fiction. It is a constituent of the FTSE SmallCap Index. Bloomsbury's head office is located in London, United Kingdom.",
    founded: 1986,
    headquarters: "London, UK",
    website: "https://www.bloomsbury.com",
    verified: true,
  },
  {
    id: "8",
    name: "Oxford University Press",
    logo: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=1290&auto=format&fit=crop",
    description: "Oxford University Press is the university press of the University of Oxford. It is the largest university press in the world, and its printing history dates back to the 1480s.",
    founded: 1586,
    headquarters: "Oxford, UK",
    website: "https://global.oup.com",
    verified: true,
  }
];
